# Generated by Django 3.2.5 on 2022-03-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0003_rename_patied_id_doctor_availability_booked_patient_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='payments',
            fields=[
                ('patient_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('admit_fee', models.IntegerField()),
                ('discharge_fee', models.IntegerField()),
                ('supplies_fee', models.IntegerField()),
                ('consultation_fee', models.IntegerField()),
                ('overall_payment', models.IntegerField()),
            ],
        ),
    ]
