# Generated by Django 3.2.5 on 2022-03-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0005_alter_records_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='document_type',
            field=models.CharField(choices=[('D', 'Diagnosis'), ('P', 'Prescription'), ('L', 'LabReport')], max_length=1),
        ),
    ]
